//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subway.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daejeon
    {
        public System.DateTime 날짜 { get; set; }
        public int 역번호 { get; set; }
        public string 역명 { get; set; }
        public string 구분 { get; set; }
        public Nullable<int> 승객수 { get; set; }
    }
}
